### ISSUE TITLE
Falha por não encontrar o GET

### ISSUE THREAD

**Issue by nazareno** [analytics-ufcg/rcongresso#1]
```
> library(RCongresso)
> 
> x = RCongresso::get_proposition(1057)
Error in RCongresso::get_proposition(1057) : 
  não foi possível encontrar a função "GET"
```

**Comment by nazareno** [comment]
A propósito, não entendi de qual pacote é a `GET`, mas que tal usar o `httr`?

**Comment by paul0vinicius** [comment]
O pacote é o _httr_ mesmo, porém eu achava que só colocar as dependências no arquivo _DESCRIPTION_ iria resolver o problema. Vou corrigí-lo assim que possível.

**Comment by paul0vinicius** [comment]
O problema era que eu estava referenciando a função do _httr_ apenas como _GET_ e dentro das funções é necessário fazer a chamada completa _httr::GET()_. O problema foi resolvido e a biblioteca está executando as funções corretamente.
