### ISSUE TITLE
Dados parlamentares incorretos na votação (Erro na API)

### ISSUE THREAD

**Issue by paul0vinicius** [analytics-ufcg/rcongresso#11]
Ao recuperar os dados da API, ela retorna os dados do partido atual e não o do partido cuja data da votação fora realizada. 

Por exemplo, nos votos da PEC171 da votação ocorrida no dia 30/06/2015, a deputada Luiza Erundina era filiada ao partido PSB. Porém, ao fazer uma consulta dos votos utilizando a API ele retorna que a candidata era filiada ao PSOL. Eu acho que por baixo dos panos, a API faz uma consulta direta usando a função para pegar os detalhes de um deputado e joga partido atual como se fosse o da época em que a votação ocorreu.

**Comment by nazareno** [comment]
Bem notado. Em algum lugar tem o histórico de filiações dos deputados?
Em qua, 23 de ago de 2017 às 11:37, Paulo Vinicius Soares <
notifications@github.com> escreveu:

**Comment by paul0vinicius** [comment]
Sim, acabei de verificar isso. Ao fazer uma chamada usando `curl -X GET "https://dadosabertos.camara.leg.br/api/v2/deputados?id=74784&ordem=ASC&ordenarPor=nome" -H  "accept: application/json"`, usando `74784` que é o ID da deputada Erundina, temos essa resposta:

```
{
  "dados": [
    {
      "id": 74784,
      "uri": "https://dadosabertos.camara.leg.br/api/v2/deputados/74784",
      "nome": "LUIZA ERUNDINA",
      "siglaPartido": "PSB",
      "uriPartido": "https://dadosabertos.camara.leg.br/api/v2/partidos/36832",
      "siglaUf": "SP",
      "idLegislatura": 52,
      "urlFoto": "http://www.camara.leg.br/internet/deputado/bandep/74784.jpg"
    },
    {
      "id": 74784,
      "uri": "https://dadosabertos.camara.leg.br/api/v2/deputados/74784",
      "nome": "LUIZA ERUNDINA",
      "siglaPartido": "PSB",
      "uriPartido": "https://dadosabertos.camara.leg.br/api/v2/partidos/36832",
      "siglaUf": "SP",
      "idLegislatura": 53,
      "urlFoto": "http://www.camara.leg.br/internet/deputado/bandep/74784.jpg"
    },
    {
      "id": 74784,
      "uri": "https://dadosabertos.camara.leg.br/api/v2/deputados/74784",
      "nome": "LUIZA ERUNDINA",
      "siglaPartido": "PSB",
      "uriPartido": "https://dadosabertos.camara.leg.br/api/v2/partidos/36832",
      "siglaUf": "SP",
      "idLegislatura": 54,
      "urlFoto": "http://www.camara.leg.br/internet/deputado/bandep/74784.jpg"
    },
    {
      "id": 74784,
      "uri": "https://dadosabertos.camara.leg.br/api/v2/deputados/74784",
      "nome": "LUIZA ERUNDINA",
      "siglaPartido": "PSOL",
      "uriPartido": "https://dadosabertos.camara.leg.br/api/v2/partidos/36839",
      "siglaUf": "SP",
      "idLegislatura": 55,
      "urlFoto": "http://www.camara.leg.br/internet/deputado/bandep/74784.jpg"
    }
```

Essa é uma lista de todas as legislaturas dela, mas eu não sei se há uma forma de mapear essas legislaturas com a data da votação. Será que esse idLegislatura tem um período de tempo? Por exemplo, 54 significa que foi de 2010~2014, 55 significa 2014~2018... etc? (Eu sei que 55 é o idLegislatura para o período atual)

**Comment by nazareno** [comment]
Na API anterior, tinha dados sobre filiações partidárias anteriores à atual do deputado. Vê o exemplo em http://www.camara.leg.br/SitCamaraWS/Deputados.asmx/ObterDetalhesDeputado?ideCadastro=141428&numLegislatura= e procura por partidoanterior no xml.

**Comment by paul0vinicius** [comment]
Vi agora. Na nova versão da API não temos acesso à esses dados. Então eu posso utilizar a partir daqui mesmo? Crio uma nova função? O que faço, exatamente?
Ainda assim, não temos a data associada para _linkar_ com a votação, só temos o histórico :/

**Comment by paul0vinicius** [comment]
Resolvido em https://github.com/labhackercd/dados-abertos/issues/100
