### ISSUE TITLE
Erro ao pegar menos de 400 votos

### ISSUE THREAD

**Issue by paul0vinicius** [analytics-ufcg/rcongresso#13]
Bug ocorre na função fetch_votos() ao percorrer o loop e tentar pegar a última página. Como a última página (5) é vazia, ele não consegue retornar isso como um dataframe e retorna uma lista vazia e gera um erro no `dplyr::do`

**Comment by nazareno** [comment]
é, nesse caso ou vira um while ou uma recursão (a chamada pra pegar a
página 1 percebe que precisa pegar a página 2, e assim por diante)
