### ISSUE TITLE
Instruções de instalação no README.md

### ISSUE THREAD

**Issue by nazareno** [analytics-ufcg/rcongresso#2]

**Comment by nazareno** [comment]
estilo https://github.com/analytics-ufcg/rsagrespb e https://github.com/analytics-ufcg/busminer

**Comment by paul0vinicius** [comment]
Professor, eu posso citar os métodos que estão disponíveis no pacote no README.md? Ou isso fica na documentação mesmo que eu gerar?

Por exemplo:

get_all_propositions( ): Retorna um dataframe contendo todas as proposições disponíveis no banco de dados da Câmara dos Deputados.
...
...

**Comment by nazareno** [comment]
Fica na documentação, Paulo
