### ISSUE TITLE
Adicionar mais exemplos no README

### ISSUE THREAD

**Issue by nazareno** [analytics-ufcg/rcongresso#21]
Um ou dois estilo: 

```
fetch_id_proposicao(tipo = "PL",
                    numero = 1057, 
                    ano = 2007) %>% 
  fetch_proposicao(id) %>% 
  fetch_votacoes(id) %>% 
  ultima_votacao() %>% 
  fetch_votacao(id)
```

de preferência com a entrada inicial vetorizada, como 

```
fetch_id_proposicao(tipo   = c("PEC", "PL"), 
                    numero = c(171, 1057),
                    ano    = c(1993, 2007)) %>% 
...
```

**Comment by nazareno** [comment]
Me toquei aqui agora que meu exemplo não faz sentido. Como não é um processo de transformação de data frames, e sim de a partir de uns criar outros, se formos deixar em pipeline, precisa ser algo como 

```
library(rcongresso)
library(purrr)
library(dplyr)

tibble(tipo   = c("PEC", "PL"), 
       numero = c(171, 1057),
       ano    = c(1993, 2007)) %>% 
  pmap(fetch_id_proposicao) %>% 
  map_int(~ (fetch_proposicao(.) %>% pull(id))) %>% 
  map_df(~ fetch_votacoes(.)) %>% 
  ultima_votacao() %>% 
  pull(id) %>% 
  map_df(~ fetch_votos(.))
``` 

Esse funciona. Tem como deixá-lo mais fácil de compreender?

**Comment by nazareno** [comment]
Tentei aqui. Não sei ainda se deveria estar (só) no README, ou em uma vignette: 

```
library(rcongresso)
library(purrr)
library(dplyr)

proposicoes = frame_data(
  ~tipo, ~numero, ~ano, 
  "PEC", 171,     1993, 
  "PL",  1057,    2007
) %>% 
  pmap(fetch_id_proposicao) %>% 
  map_df(~ (fetch_proposicao(.))) 

votos = proposicoes %>% 
  mutate(id_votacao = map_int(id, ~ fetch_votacoes(.) %>% 
                                ultima_votacao() %>% 
                                pull(id))) %>% 
  mutate(votos = map(id_votacao, ~ fetch_votos(.))) %>% 
  unnest(votos)

votos %>% 
  group_by(siglaTipo, numero, ano, voto) %>% 
  count()
```

**Comment by nazareno** [comment]
Mais uma tentativa: 

```
library(rcongresso)
library(purrr)
library(dplyr)
library(ggplot2)

fetch_id_ultima_votacao = function(id_proposicao){
  fetch_votacoes(id_proposicao) %>% 
    ultima_votacao() %>% 
    pull(id)
}

proposicoes = frame_data(
  ~tipo, ~numero, ~ano, 
  "PEC", 171,     1993, 
  "PL",  1057,    2007
) %>% 
  pmap(fetch_id_proposicao) %>% 
  map_df(~ (fetch_proposicao(.))) 

votos = proposicoes %>% 
  mutate(id_votacao = map_int(id, ~ fetch_id_ultima_votacao(.))) %>% 
  mutate(votos = map(id_votacao, ~ fetch_votos(.))) %>% 
  unnest(votos)

votos %>% 
  group_by(siglaTipo, numero, ano, voto) %>% 
  count() %>% 
  ggplot(aes(x = paste(siglaTipo, numero, ano), y = n, fill = voto)) + 
  geom_col()

```

Vignette? Tem um exemplo menor que possa ir pro README?

**Comment by paul0vinicius** [comment]
Eu acho que esse se encaixaria mais em uma _vignette_. Por definição, a _vignette_ é um demonstração simples de uma aplicação prática cujo pacote se dispõe a resolver. As _vignettes_ do QMR são bons exemplos disso.

Exemplos de uso no README são exemplos simples demonstrando o uso das funções do pacote em si. Algo como utilizar a função que mostra o gasto dos deputados, ou as proposições feitas entre um período de tempo, pegar algumas votações e ver o voto de cada deputado...

**Comment by paul0vinicius** [comment]
Eu posso escrever uma _vignette_ com esse exemplo, mas eu acho que não entendi muito bem o que ele faz. Ele faz um _count_ dos votos pra ver a diferença entre 'sim', 'não' e 'obstrução'?

**Comment by nazareno** [comment]
Exato. Ele plota um gráfico mostrando quantos votos sim/não/etc. houve para
cada proposição de um conjunto inicial de proposições. Pra isso ele tem que
recuperar as proposições e os votos das últimas votações de cada
proposição.

E concordei com o vignette, mas ainda acho que precisamos de um ou dois
exemplos curtos e que motivem as pessoas no README :)

**Comment by paul0vinicius** [comment]
Eu acho que pegar uma votação seria uma boa, mostrar os campos da votação ou as informações de um deputado. Os exemplos no [dplyr](https://github.com/tidyverse/dplyr) mostram uma aplicação para cada função existente no pacote. Acho que poderíamos fazer algo nesse sentido.

Os exemplos podem ser os mesmos da documentação do código?

**Comment by nazareno** [comment]
Sobre o que cada parte do exemplo antes faz: 

```
# Todos os dados sobre um conjunto de proposições
proposicoes = frame_data(
  ~tipo, ~numero, ~ano, 
  "PEC", 171,     1993, 
  "PL",  1057,    2007
) %>% 
  pmap(fetch_id_proposicao) %>% 
  map_df(~ (fetch_proposicao(.))) 

# Os votos dos deputados na última votação de cada proposição
votos = proposicoes %>% 
  mutate(id_votacao = map_int(id, ~ fetch_id_ultima_votacao(.))) %>% 
  mutate(votos = map(id_votacao, ~ fetch_votos(.))) %>% 
  unnest(votos)

# Vendo os votos
votos %>% 
  group_by(siglaTipo, numero, ano, voto) %>% 
  count() %>% 
  ggplot(aes(x = paste(siglaTipo, numero, ano), y = n, fill = voto)) + 
  geom_col()
```

**Comment by nazareno** [comment]
Pra mim os exemplos do README tem que ser algo simples, útil e que motive a usar o pacote. 

Exemplos: https://github.com/hadley/rvest  e https://github.com/jtleek/slipper

**Comment by paul0vinicius** [comment]
Professor, eu tava procurando pacotes que também fossem _API wrappers_ para verificar se existe algum padrão de exemplos nesse caso, mas não achei nada muito sofisticado. O exemplo que eu achei foi um pacote R para a API do [Pinterest](https://github.com/ColinFay/rpinterest).
Pensei em juntar os exemplos acima com uma descrição das funções disponíveis do pacote tal qual estão descritas no link acima, sempre alinhando com as funções da API da Câmara. O que acha?

**Comment by nazareno** [comment]
Eu acho que não precisa duplicar a documentação no rearme. Como estamos sem
saber escolher um exemplo, sugiro deixar sem por agora. Fazer a release 0.1
sem.
Em qua, 4 de out de 2017 às 08:38, Paulo Vinicius Soares <
notifications@github.com> escreveu:
