### ISSUE TITLE
Mudar vignette das múltiplas props

### ISSUE THREAD

**Issue by nazareno** [analytics-ufcg/rcongresso#26]
Esse vignette não deve mais usar o script R linha de comando. Ele pode usar o exemplo com purrr que sugeri. E o nome dele não precisa fazer referência ao QMR.

**Comment by nazareno** [comment]
Criei um vignette purrr + rcongresso que acho que cobre a análise de várias proposições.

**Comment by paul0vinicius** [comment]
Acabei de dar uma olhada e ficou bem bacana! 
Acho que a única ressalva que eu faria seria na análise na diferença de votos entre homens e mulheres. Uma análise relativa ficaria mais clara. Uma análise absoluta fica meio difícil de ler porque existem mais homens do que mulheres na câmara, aí fica meio discrepante lá na hora de ver.

**Comment by nazareno** [comment]
É verdade. Mas achei que ia complicar o código. Como é mais um exemplo de
como cruzar os dados que de análise de fato, sugiro deixar assim.
Em qua, 4 de out de 2017 às 09:18, Paulo Vinicius Soares <
notifications@github.com> escreveu:

**Comment by nazareno** [comment]
Fica faltando ainda reformular ou remover a vignette que tínhamos. o pega_votacoes.R sugiro levar para o repo do QMR

**Comment by paul0vinicius** [comment]
Na versão que eu tinha colocado na outra branch, eu tinha "excluído" o script e a pasta examples e o _vignette_ qmr-multiplas-votacoes tinha se tornado justamente a explicação do funcionamento do script. Eu deixo a _vignette_ lá e apenas mudo o nome?

**Comment by paul0vinicius** [comment]
Eu acho que entendi agora! No caso, acho melhor remover essa _vignette_ mesmo e deixar apenas aquela de introdução para explicar a organização dos dados. Concordo sobre mover o _script_ para o repo do QMR.

**Comment by paul0vinicius** [comment]
Vou adicionar um hiperlink na _vignette_ do _purrr_ para a introdução de como os dados estão organizados. Eu acho que é fundamental antes de mexer nos dados.
