### ISSUE TITLE
fetch_proposicoes

### ISSUE THREAD

**Issue by nazareno** [analytics-ufcg/rcongresso#29]
para a v0.2, seria muito útil ter essa função, baseada no endpoint `/proposicoes`

**Comment by paul0vinicius** [comment]
Está quase feito, só falta ajustar a documentação e criar outra função que use o endpoint `/proposicoes/id` porque este retorna mais detalhes de uma proposição.
Aí faltarão os testes e documentação. Após terminar isso, abro um _pull request_.
