### ISSUE TITLE
Vetorizar gets 

### ISSUE THREAD

**Issue by nazareno** [analytics-ufcg/rcongresso#3]
Por exemplo, em `get_proposition(i)`, `i` deve poder ser um vetor de proposições. Como em R todo objeto é um vetor, é boa prática que as funções saibam operar sobre vetores.

**Comment by nazareno** [comment]
ainda está aberta essa issue?

**Comment by paul0vinicius** [comment]
Sim :/ 
Não consegui vetorizar a função `fetch_votos()`, aí reverti no commit seguinte.

O _commit_ referente à minha tentativa foi esse: https://github.com/analytics-ufcg/rcongresso/commit/b6195657bb5e2dfc81d7ec56c679d7239e6ad668
Me dá uma luz que eu tento novamente. Eu ainda to pensando muuuito procedural :/

**Comment by nazareno** [comment]
agora que fetch_votos tá feito, pronto? ou falta fetch_deputado ainda?

**Comment by paul0vinicius** [comment]
fiz todas as funções vetorizadas hoje, tava só esperando o merge e amanhã insiro essas mudanças :)
