### ISSUE TITLE
[Submissão do pacote ao CRAN] Informações do pacote devem estar em inglês

### ISSUE THREAD

**Issue by paul0vinicius** [analytics-ufcg/rcongresso#31]
Mensagem da equipe do CRAN:
```
Thanks, please write all package informations (DESCRIPTION file, Rd-files, ...) in English.

Please fix and resubmit.
```

**Comment by paul0vinicius** [comment]
O que me deixou uma dúvida: A documentação também deve estar em inglês? Ou só o nome dos arquivos?

**Comment by nazareno** [comment]
Os .Rd são os arquivos do help, né? Se sim, eles estão dizendo que o
conteúdo deles precisa ser em inglês. Que tosco :/. E pior que acho que
publicar no CRAN é importante, o que vai implicar num trabalho chato.

**Comment by paul0vinicius** [comment]
Não tem como fazer uma espécie de internacionalização pra documentação não? Apesar de dar trabalho seria a melhor maneira de abranger os dois públicos. :/
