### ISSUE TITLE
[Submissão do pacote ao CRAN] Escrever os nomes das funções em inglês

### ISSUE THREAD

**Issue by paul0vinicius** [analytics-ufcg/rcongresso#35]
```
Please write all Rd-files in English.
```

**Comment by nazareno** [comment]
Não entendi, Paulo. Será que são os nomes de função mesmo???
Em dom, 8 de out de 2017 às 13:20, Paulo Vinicius Soares <
notifications@github.com> escreveu:

**Comment by nazareno** [comment]
Talvez seja uma boa perguntar pra conferir. Porque os nomes de função
inclusive são definidos nos .R, e é estranho exigir bom inglês neles.
Em dom, 8 de out de 2017 às 15:04, Nazareno Andrade <
nazareno@computacao.ufcg.edu.br> escreveu:

**Comment by paul0vinicius** [comment]
Mas os rd-files são gerados de acordo com os nomes das funções. Por exemplo, o arquivo `fetch_deputado.Rd`  é gerado a partir da função `fetch_deputado( )` e assim sucessivamente... Aí minha suspeita é que eles também queiram os nomes em inglês.

**Comment by nazareno** [comment]
Tem como perguntar pra eles? Pela frase deles não está claro que é o nome
do arquivo o problema.
Em dom, 8 de out de 2017 às 22:52, Paulo Vinicius Soares <
notifications@github.com> escreveu:

**Comment by paul0vinicius** [comment]
Eu mandei um email para a moça que fez a correção do pacote e vou esperar a resposta dela, mas assim, a descrição das funções já estava toda em inglês. Chequei agora e tudo está em inglês, exceto o nome dos arquivos. Por isso acho que pode ser isso, mas concordo que está ambiguo.

**Comment by paul0vinicius** [comment]
O problema foi na documentação gerada. Aparentemente não estava atualizada e tinha apenas uma função que não fora traduzida... Agora está tudo atualizado e o site também. O pacote foi resubmetido e está aguardando o feedback.
