### ISSUE TITLE
fetch_deputados

### ISSUE THREAD

**Issue by joaoarthurbm** [analytics-ufcg/rcongresso#36]
Seria legal ter a função para recuperar os deputados baseada nesse serviço: https://dadosabertos.camara.leg.br/api/v2/deputados

Obs.: o serviço é paginado.

**Comment by paul0vinicius** [comment]
Olá, João!

Uma melhoria semelhante está em desenvolvimento para que a função `fetch_proposicao()` utilize o _endpoint_ `/proposicoes`. Dado isso, acredito que a função `fetch_deputados()` também passe por essa melhoria na próxima semana e de forma mais rápida, já que as soluções são parecidas.

Atenciosamente,
