### ISSUE TITLE
Documentação para parâmetros de fetch_proposicao

### ISSUE THREAD

**Issue by nazareno** [analytics-ufcg/rcongresso#42]
Explicar que quando usamos `id` não faz sentido usar as demais. 

Explicar como recuperar todas as proposições que satisfazem os critérios  - atualmente parece que o máximo é 100. 

Queremos mesmo expor o parâmetro pagina? Acho que não. 

O que é `codPartido` ? 

Qual o formato das datas? 

Talvez uma pequena vignette ajude?

**Comment by nazareno** [comment]
o que exatamente são `ano` e `dataInicio`/ `dataFim` ? `ano` é da criação da proposição, é?

**Comment by paul0vinicius** [comment]
> Explicar que quando usamos id não faz sentido usar as demais.

Certinho.

> Explicar como recuperar todas as proposições que satisfazem os critérios - atualmente parece que o máximo é 100.

Se não me engano, é 100 por página. Aí você vai navegando até encontrar o resultado que te satisfaça.

> Queremos mesmo expor o parâmetro pagina? Acho que não.

Hmm, Então uma forma de recuperar os dados seria passando a quantidade de itens e essa navegação das páginas ser transparente?

> O que é codPartido ?

Os partidos são uma espécie de _enum_, daí esse código do partido é o número referente ao _enum_.

> Qual o formato das datas?

Acredito que com /, mas não existe essa documentação na plataforma. Eu testei com as barras na API diretamente e funcionou.

> Talvez uma pequena vignette ajude?

É uma boa ideia. O problema geral é que a documentação da própria API não é muito explicativa em como utilizar as funções.

Essa `dataInicio` e `dataFim` eu fiquei muito em dúvida, mas acredito que seja o intervalo de tempo da tramitação da API. Me baseei pela [API antiga](http://www2.camara.leg.br/transparencia/dados-abertos/dados-abertos-legislativo/webservices/proposicoes-1/listarProposicoesTramitadasNoPeriodo) onde estes parâmetros são utilizados dessa forma.

`ano` é a data da criação da proposição, tal como `"PEC", 171, 1993".

**Comment by paul0vinicius** [comment]
resolvido em 97312f6d8980f81e7fc8d45957e43dc795f23e8897312f6d8980f81e7fc8d45957e43dc795f23e88
