### ISSUE TITLE
Documentação usando ROxygen e exemplos

### ISSUE THREAD

**Issue by nazareno** [analytics-ufcg/rcongresso#5]
Mudar nossa documentação das funções públicas ao menos para o ROxygen, e incluir sempre uma diretiva `@example`, além de `@references` para a documentação da câmara. 

Bons exemplos: 

https://github.com/hadley/ggplot2movies/blob/master/R/movies.R

https://github.com/tidyverse/dplyr/blob/master/R/nth-value.R

**Comment by paul0vinicius** [comment]
Commitei agora com a documentação, mas percebi que ainda faltam as referências, por isso ainda não fechei essa issue.

**Comment by paul0vinicius** [comment]
Professor, todas as funções podem ser encontradas nesse link: https://dadosabertos.camara.leg.br/swagger/api.html. A descrição e modo de funcionamento, etc

Seria melhor colocar um único `@references`apontando para esse link, certo? Em qual arquivo eu coloco isso?

**Comment by nazareno** [comment]
Sim!
Pode ser no help do pacote.

**Comment by paul0vinicius** [comment]
O _help_ do pacote é um arquivo? Eu procurei, mas não achei exemplos. É um arquivo _.md_?

**Comment by nazareno** [comment]
é o que aparece quando você digita help(package="MASS")

vê
https://support.rstudio.com/hc/en-us/articles/200532317-Writing-Package-Documentation
e
https://cran.r-project.org/doc/manuals/R-exts.html#Documenting-packages
