### ISSUE TITLE
Tratar IDs repetidas ao invés de dar erro 404?

### ISSUE THREAD

**Issue by andresmrm** [analytics-ufcg/rcongresso#79]
Atualmente, aparentemente, se der um `fetch_tramitacao` com um vetor de IDs em que algum valor é repetido dá erro 404.

Parece ser fácil de resolver o problema, apenas passando por um `unique`.

Minha questão é se esse unique deveria ser feito pela RCongresso, ou se a mensagem de erro deveria ser mais descritiva.

É provável que o mesmo problema afete outras funções da lib.

### Passos para reproduzir o erro:
> fetch_tramitacao(c("2175303", "2175303"))
> Error: Falha na requisicao a API dos Dados Abertos. Erro 404 ao tentar acessar: > https://dadosabertos.camara.leg.br/api/v2/proposicoes/2175303/tramitacoes/api/v2/proposicoes/2175303/tramitacoes 

### Versão do Sistema Operacional e do R:
Arch Linux - R version 3.5.0

**Comment by andresmrm** [comment]
Obrigado!
Se quiser posso fazer um PR arrumando isso.

**Comment by paul0vinicius** [comment]
Aceito sim, seria ótimo!

**Comment by andresmrm** [comment]
Veja o que você acha do código que coloquei no PR.

**Comment by paul0vinicius** [comment]
Prontinho. Aproveitei e corrigi a outra função `fetch_relacionadas()` que estava com o mesmo erro. Obrigado pela contribuição nos testes também :)

**Comment by andresmrm** [comment]
Eu que agradeço!
=D
