### ISSUE TITLE
Bug em fetch_deputado()

### ISSUE THREAD

**Issue by hadrizia** [analytics-ufcg/rcongresso#94]
Quando executo dentro do pacote, a função funciona. Mas ao executar externamente, com `rcongresso::fetch_deputado(id = 160559)`

Dá o seguinte erro:

 ```
Unexpected columns: 
   redeSocial 
Error in FUN1(.) : could not find function "FUN1"
```

**Comment by andresmrm** [comment]
Hmm, pelo que já passei por esse erro antes, deve ser só adicionar a coluna
"redeSocial" nas colunas esperadas para essa função.
