### ISSUE TITLE
Lei de id 129808 não funciona em fetch_proposicao_senado

### ISSUE THREAD

**Issue by thayannevls** [analytics-ufcg/rcongresso#95]
### Comportamento esperado:
Que retornasse dataframe contendo informaçõe da proposição
### Comportamento real:
Retorna erro de 
```
Not found columns: 
   apelido_materia
   sigla_casa_leitura
   nome_casa_leitura 

 Unexpected columns: 
   codigo_natureza
   nome_natureza
   descricao_natureza 
Error in FUN1(.) : could not find function "FUN1"
```
### Passos para reproduzir o erro:
```
rcongresso::fetch_proposicao_senado(129808)
```

**Comment by andresmrm** [comment]
Parece ser um erro equivalente a esse: https://github.com/analytics-ufcg/rcongresso/issues/94
Deve ser só adicionar as `Unexpected columns` lá nas constantes da função.
Talvez eles ainda estejam modificando a API.

**Comment by danielrcoura** [comment]
Vou verificar
