### ISSUE TITLE
Bugs no fetch_proposicao_camara e fetch_proposicao_senado

### ISSUE THREAD

**Issue by tarcisocomp** [analytics-ufcg/rcongresso#99]
Agora usa a função do `rcongresso`

Alguns proposiões não estão funcionando porque algo está acontecendo no rcongresso...

Lista das que identifiquei:

* Senado
  
  * 129808
  * 133943
  * 127753
* Câmara
  
  * 257161

**Comment by jairNeto** [comment]
Irei ajeitar
